#ifndef LIGHT_BELT_ESP32_NODE_9_H
#define LIGHT_BELT_ESP32_NODE_9_H

#define NODE_ID 9
#define NODE_IPV4_D 209
#define OUTPUT_COUNT 1
#define OUTPUT_0_ID 1
#define OUTPUT_0_GPIO 4
#define OUTPUT_0_PIXELS 20

#endif
