#ifndef LIGHT_BELT_ESP32_NODE_1_H
#define LIGHT_BELT_ESP32_NODE_1_H

#define NODE_ID 1
#define NODE_IPV4_D 201
#define OUTPUT_COUNT 1
#define OUTPUT_0_ID 1
#define OUTPUT_0_GPIO 4
#define OUTPUT_0_PIXELS 10

#endif
