#ifndef LIGHT_BELT_ESP32_NODE_5_H
#define LIGHT_BELT_ESP32_NODE_5_H

#define NODE_ID 5
#define NODE_IPV4_D 205
#define OUTPUT_COUNT 1
#define OUTPUT_0_ID 1
#define OUTPUT_0_GPIO 4
#define OUTPUT_0_PIXELS 40

#endif
