#!/usr/bin/env python3
"""Resolve the nine WLED/DDP nodes through Avahi into a runtime profile.

The tracked template retains the stable logical-strip mDNS names.  This tool
copies it to an ignored runtime path, replacing resolved names with current
IPv4 addresses.  A name that Avahi cannot resolve is explicitly disabled so
DDP skips that node while the remaining strip vocabulary stays available.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import ipaddress
import os
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Callable

import yaml


Runner = Callable[[list[str], int], str]


def log(message: str) -> None:
    print(f"[resolve_nodes] {message}", file=sys.stderr, flush=True)


def run(command: list[str], timeout: int = 10) -> str:
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout if result.returncode == 0 else ""


def mdns_name(strip_id: str) -> str:
    """Return the required unique WLED hostname for one logical strip."""
    if not strip_id.startswith("strip_") or not strip_id[6:]:
        raise ValueError(f"expected logical strip_<label>, got {strip_id!r}")
    return f"wled-strip-{strip_id[6:]}.local"


def resolve_avahi(hostname: str, runner: Runner = run) -> str | None:
    """Resolve exactly one local hostname without a DNS/IP fallback."""
    output = runner(["avahi-resolve", "-4", "-n", hostname], 10)
    for line in output.splitlines():
        fields = line.split()
        if len(fields) >= 2 and fields[0].rstrip(".") == hostname.rstrip("."):
            try:
                return str(ipaddress.IPv4Address(fields[1]))
            except ipaddress.AddressValueError:
                continue
    return None


def resolve_profile(template: Path, output: Path, runner: Runner = run) -> int:
    """Write one ignored runtime profile and return its disabled-node count."""
    if template.resolve() == output.resolve():
        raise ValueError("runtime profile output must not overwrite its template")
    if is_git_tracked(output, template.parents[2]):
        raise ValueError(f"runtime profile output is Git tracked: {output}")

    profile = yaml.safe_load(template.read_text(encoding="utf-8"))
    nodes = profile.get("layout", {}).get("digital_nodes", [])
    outputs = profile.get("layout", {}).get("digital_outputs", [])
    strip_by_node = {item["node_id"]: item["strip_id"] for item in outputs}
    if len(nodes) != 9 or len(strip_by_node) != 9:
        raise ValueError("template must contain nine independent digital nodes and outputs")

    resolution_requests: list[tuple[dict, str, str]] = []
    for node in nodes:
        strip_id = strip_by_node.get(node.get("node_id"))
        if strip_id is None:
            raise ValueError(f"node {node.get('node_id')!r} has no logical strip")
        hostname = mdns_name(strip_id)
        resolution_requests.append((node, strip_id, hostname))

    with ThreadPoolExecutor(max_workers=min(9, len(resolution_requests))) as executor:
        addresses = list(executor.map(lambda item: resolve_avahi(item[2], runner), resolution_requests))

    disabled = 0
    for (node, strip_id, hostname), address in zip(resolution_requests, addresses):
        node["host"] = address or hostname
        node["enabled"] = address is not None
        if address is None:
            disabled += 1
            log(f"node {node['node_id']} {strip_id}: disabled (mDNS unresolved)")
        else:
            log(f"node {node['node_id']} {strip_id}: {hostname} -> {address}")

    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.{uuid.uuid4().hex}.tmp")
    try:
        temporary.write_text(
            "# Generated by scripts/resolve_nodes.py. Do not edit.\n"
            f"# template: {template}\n"
            + yaml.safe_dump(profile, allow_unicode=False, sort_keys=False),
            encoding="utf-8",
        )
        os.replace(temporary, output)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
    return disabled


def is_git_tracked(path: Path, repo_root: Path) -> bool:
    try:
        relative = path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        return False
    result = subprocess.run(
        ["git", "ls-files", "--error-unmatch", "--", str(relative)],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Create the WLED DDP runtime profile via Avahi")
    parser.add_argument(
        "--template",
        type=Path,
        default=root / "config" / "profiles" / "rk3588-host-service.yaml",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=root / "config" / "runtime" / "wled-ddp-mdns.yaml",
    )
    parser.add_argument("--check", action="store_true", help="resolve and report without writing")
    args = parser.parse_args()

    if args.check:
        profile = yaml.safe_load(args.template.read_text(encoding="utf-8"))
        outputs = profile["layout"]["digital_outputs"]
        for item in outputs:
            hostname = mdns_name(item["strip_id"])
            address = resolve_avahi(hostname)
            state = address if address is not None else "disabled (mDNS unresolved)"
            print(f"node {item['node_id']} {item['strip_id']}: {state}")
        return 0

    disabled = resolve_profile(args.template, args.out)
    log(f"wrote {args.out}; disabled {disabled}/9 nodes")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # Keep Host startup explicit, never claim success.
        log(f"failed: {type(exc).__name__}: {exc}")
        raise SystemExit(1)
